# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(525, 475)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 230, 161, 61))
        self.pushButton.setObjectName("pushButton")
        self.lblresult = QtWidgets.QLabel(self.centralwidget)
        self.lblresult.setGeometry(QtCore.QRect(50, 310, 141, 101))
        self.lblresult.setText("")
        self.lblresult.setObjectName("lblresult")
        self.grouphobiler = QtWidgets.QGroupBox(self.centralwidget)
        self.grouphobiler.setGeometry(QtCore.QRect(20, 10, 221, 221))
        self.grouphobiler.setObjectName("grouphobiler")
        self.layoutWidget = QtWidgets.QWidget(self.grouphobiler)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 201, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbsinema = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbsinema.setObjectName("cbsinema")
        self.verticalLayout.addWidget(self.cbsinema)
        self.cbkitapokumak = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbkitapokumak.setObjectName("cbkitapokumak")
        self.verticalLayout.addWidget(self.cbkitapokumak)
        self.cbspor = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbspor.setObjectName("cbspor")
        self.verticalLayout.addWidget(self.cbspor)
        self.grouphobiler_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.grouphobiler_2.setGeometry(QtCore.QRect(280, 10, 221, 221))
        self.grouphobiler_2.setObjectName("grouphobiler_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.grouphobiler_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 40, 201, 151))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbsinema_2 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.cbsinema_2.setObjectName("cbsinema_2")
        self.verticalLayout_2.addWidget(self.cbsinema_2)
        self.cbkitapokumak_2 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.cbkitapokumak_2.setObjectName("cbkitapokumak_2")
        self.verticalLayout_2.addWidget(self.cbkitapokumak_2)
        self.cbspor_2 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.cbspor_2.setObjectName("cbspor_2")
        self.verticalLayout_2.addWidget(self.cbspor_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 230, 161, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lblresult_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblresult_2.setGeometry(QtCore.QRect(310, 300, 161, 111))
        self.lblresult_2.setText("")
        self.lblresult_2.setObjectName("lblresult_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 525, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "secilenleri al"))
        self.grouphobiler.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbsinema.setText(_translate("MainWindow", "sinema"))
        self.cbkitapokumak.setText(_translate("MainWindow", "kitap okumak"))
        self.cbspor.setText(_translate("MainWindow", "spor"))
        self.grouphobiler_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbsinema_2.setText(_translate("MainWindow", "web tasarım"))
        self.cbkitapokumak_2.setText(_translate("MainWindow", "programlama"))
        self.cbspor_2.setText(_translate("MainWindow", "matematik"))
        self.pushButton_2.setText(_translate("MainWindow", "secilenleri al"))
