# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitleds.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(477, 589)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cbsehirler = QtWidgets.QComboBox(self.centralwidget)
        self.cbsehirler.setGeometry(QtCore.QRect(50, 100, 221, 71))
        self.cbsehirler.setObjectName("cbsehirler")
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(290, 100, 161, 61))
        self.lbl_result.setObjectName("lbl_result")
        self.btngetitem = QtWidgets.QPushButton(self.centralwidget)
        self.btngetitem.setGeometry(QtCore.QRect(50, 210, 171, 71))
        self.btngetitem.setObjectName("btngetitem")
        self.btnloaditem = QtWidgets.QPushButton(self.centralwidget)
        self.btnloaditem.setGeometry(QtCore.QRect(260, 210, 171, 71))
        self.btnloaditem.setObjectName("btnloaditem")
        self.btnclearitem = QtWidgets.QPushButton(self.centralwidget)
        self.btnclearitem.setGeometry(QtCore.QRect(50, 300, 171, 71))
        self.btnclearitem.setObjectName("btnclearitem")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 477, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_result.setText(_translate("MainWindow", "TextLabel"))
        self.btngetitem.setText(_translate("MainWindow", "Get item"))
        self.btnloaditem.setText(_translate("MainWindow", "load item"))
        self.btnclearitem.setText(_translate("MainWindow", "clear item"))
