# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_listform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(588, 515)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(320, 30, 131, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnadd = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnadd.setObjectName("btnadd")
        self.verticalLayout.addWidget(self.btnadd)
        self.btnedit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnedit.setObjectName("btnedit")
        self.verticalLayout.addWidget(self.btnedit)
        self.btnremove = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnremove.setObjectName("btnremove")
        self.verticalLayout.addWidget(self.btnremove)
        self.btnup = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnup.setObjectName("btnup")
        self.verticalLayout.addWidget(self.btnup)
        self.btndown = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btndown.setObjectName("btndown")
        self.verticalLayout.addWidget(self.btndown)
        self.btnsort = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnsort.setObjectName("btnsort")
        self.verticalLayout.addWidget(self.btnsort)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btnexit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnexit.setObjectName("btnexit")
        self.verticalLayout.addWidget(self.btnexit)
        self.listItems = QtWidgets.QListWidget(self.centralwidget)
        self.listItems.setGeometry(QtCore.QRect(20, 30, 261, 361))
        self.listItems.setObjectName("listItems")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 588, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnadd.setText(_translate("MainWindow", "add"))
        self.btnedit.setText(_translate("MainWindow", "edit"))
        self.btnremove.setText(_translate("MainWindow", "remove"))
        self.btnup.setText(_translate("MainWindow", "up"))
        self.btndown.setText(_translate("MainWindow", "down"))
        self.btnsort.setText(_translate("MainWindow", "sort"))
        self.btnexit.setText(_translate("MainWindow", "exit"))
